/* RafayLab — Credit Changer */
(function () {
    'use strict';

    const origEl = document.getElementById('creditOriginal');
    const newEl = document.getElementById('creditNew');
    const fileEl = document.getElementById('creditFile');
    const descEl = document.getElementById('creditDesc');
    const verEl = document.getElementById('creditVersion');
    const licEl = document.getElementById('creditLicense');
    const applyBtn = document.getElementById('applyBtn');
    const copyBtn = document.getElementById('copyMetaBtn');
    const downloadBtn = document.getElementById('downloadMetaBtn');
    const output = document.getElementById('creditOutput');
    const codeOut = document.getElementById('creditCode');
    const guideOut = document.getElementById('creditGuide');

    function generate() {
        const orig = origEl.value.trim() || 'Unknown';
        const nw = newEl.value.trim() || 'Rafay';
        const file = fileEl.value.trim() || 'mod.pak';
        const desc = descEl.value.trim() || 'Custom mod';
        const ver = verEl.value.trim() || '1.0.0';
        const lic = licEl.value.trim() || 'MIT';
        const date = new Date().toISOString();

        const meta = [
            '# ==========================================',
            '# RafayLab — Modified Metadata',
            '# ==========================================',
            '# File: ' + file,
            '# Original Author: ' + orig,
            '# Modified by: ' + nw,
            '# Description: ' + desc,
            '# Version: ' + ver,
            '# License: ' + lic,
            '# Date: ' + date,
            '# ==========================================',
            '',
            'metadata = {',
            '    "file": "' + file + '",',
            '    "original_author": "' + orig + '",',
            '    "modified_by": "' + nw + '",',
            '    "description": "' + desc + '",',
            '    "version": "' + ver + '",',
            '    "license": "' + lic + '",',
            '    "modified_date": "' + date + '",',
            '}',
            '',
            'print("Metadata generated by RafayLab")',
            'for key, val in metadata.items():',
            '    print(f"  {key}: {val}")',
            '',
            '# NOTE: This is a metadata template.',
            '# Use it with your own files or open-licensed content.',
            '# Do not remove original credits if license requires attribution.',
            ''
        ].join('\n');

        codeOut.textContent = meta;

        const guide = [
            'Original author daalo (agar pata hai)',
            'Naya author: Rafay',
            'File name: apna file ka naam',
            'Description: kya hai woh file',
            'Version + License set karo',
            'Generate Metadata dabao',
            'Copy ya Download karo',
            'NOTE: Sirf apni files ya open-licensed content pe use karo'
        ];

        guideOut.innerHTML = guide.map(function (line, i) {
            return '<div class="guide-line"><span class="guide-num">' + (i+1) + '</span><span>' + line + '</span></div>';
        }).join('');

        output.style.display = 'block';
        output.scrollIntoView({ behavior: 'smooth' });
    }

    if (applyBtn) applyBtn.addEventListener('click', generate);

    if (copyBtn) {
        copyBtn.addEventListener('click', function () {
            navigator.clipboard.writeText(codeOut.textContent).then(function () {
                copyBtn.querySelector('span').textContent = 'Copied!';
                setTimeout(function () { copyBtn.querySelector('span').textContent = 'Copy'; }, 2000);
            });
        });
    }

    if (downloadBtn) {
        downloadBtn.addEventListener('click', function () {
            const content = codeOut.textContent;
            const name = (fileEl.value.trim() || 'metadata') + '_meta.py';
            const blob = new Blob([content], { type: 'text/plain' });
            const url = URL.createObjectURL(blob);
            const a = document.createElement('a');
            a.href = url;
            a.download = name;
            document.body.appendChild(a);
            a.click();
            document.body.removeChild(a);
            URL.revokeObjectURL(url);
        });
    }

    // Initial generation
    generate();
})();
